apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
    app.kubernetes.io/name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
        app.kubernetes.io/name: payment-service
    spec:
      containers:
        - name: payment-service
          image: meshmart-service-mesh/payment-service:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8002
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
    app.kubernetes.io/name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - name: http
      port: 8002
      targetPort: 8002

